### ISSUE TITLE
Dock Tiles for Apple Apps not populating 10.15.2

### ISSUE THREAD

**Issue by CraigLindsey** [ryangball/DockBuilder#6] opened 2020-01-14 21:45 UTC
After building a package and confirming the layest version of dockutil was included, I installed through JAMF and DockBuilder ran as expected. However, none of the Apple app icons populate. I've confirmed this in a VM running 10.15.2 as well as a freshly installed 10.15.2 OS on a 16" MBP. I've tested with a local user and a mobile managed user. The issue persists.

The same .pkg behaves correctly under macOS 10.14.6

**Comment by ryangball** [comment] 2020-01-14 21:52
@CraigLindsey If this is actually an issue I will probably be able to take a look at one night, but before I do are you sure that you are using the correct paths for the Apple apps in Catalina? For reference, System Preferences lives here in Catalina: `/System/Applications/System Preferences.app`

**Comment by huyhong** [comment] 2020-01-16 00:57
To clarify what @ryangball says, a number of Apple apps still appear to live inside `/Applications/{App Name}.app` but their valid path for the Dock's purpose is `/System/Applications/{App Name}.app`. See this issue on `dockutil` for more details: https://github.com/kcrawford/dockutil/issues/86#issuecomment-546526480

**Comment by ryangball** [comment] 2020-01-16 02:20
@huyhong This was my thought as well. @CraigLindsey is this your issue?

**Comment by ryangball** [comment] 2020-01-23 11:55
Closing as I suspect the issue is related to Catalina’s system app location change.

**Closed as completed by ryangball** 2020-01-23 11:55 UTC
